http:
  host: 'localhost'

authentication:
  jwtOptions:
    privateKeyPath: config/jwt/private.pem
    publicKeyPath: config/jwt/public.pem
    phrase: config/jwt/public.pem
    algorithm: HS256,
    expiresIn: 365d
